# Generated by Django 5.2.4 on 2025-07-30 19:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthcareSystem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('system_type', models.CharField(choices=[('hospital', 'Hospital'), ('clinic', 'Clinic'), ('urgent_care', 'Urgent Care'), ('specialty_center', 'Specialty Center')], max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('emr_system', models.CharField(blank=True, max_length=50)),
                ('api_endpoint', models.URLField(blank=True)),
                ('api_credentials', models.JSONField(default=dict)),
                ('operating_hours', models.JSONField(default=dict)),
                ('emergency_services', models.BooleanField(default=False)),
                ('bed_capacity', models.IntegerField(blank=True, null=True)),
                ('current_occupancy', models.IntegerField(default=0)),
                ('subscription_plan', models.CharField(default='basic', max_length=50)),
                ('monthly_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contract_start_date', models.DateField()),
                ('contract_end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'healthcare_systems',
                'ordering': ['name'],
            },
        ),
    ]
