# Generated by Django 5.2.4 on 2025-07-30 20:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymptomCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='symptoms.symptomcategory')),
            ],
            options={
                'verbose_name_plural': 'Symptom Categories',
                'db_table': 'symptom_categories',
            },
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('keywords', models.JSONField(default=list)),
                ('severity_indicators', models.JSONField(default=list)),
                ('icd_codes', models.JSONField(default=list)),
                ('is_emergency_indicator', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptoms', to='symptoms.symptomcategory')),
            ],
            options={
                'db_table': 'symptoms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SymptomDepartmentMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.DecimalField(decimal_places=4, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('priority_order', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symptoms.symptom')),
            ],
            options={
                'db_table': 'symptom_department_mappings',
                'ordering': ['priority_order'],
                'unique_together': {('symptom', 'department')},
            },
        ),
        migrations.AddField(
            model_name='symptom',
            name='associated_departments',
            field=models.ManyToManyField(through='symptoms.SymptomDepartmentMapping', to='departments.department'),
        ),
    ]
