# Generated by Django 5.2.4 on 2025-07-30 20:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='N8NWorkflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('workflow_type', models.CharField(choices=[('symptom_analysis', 'Symptom Analysis'), ('voice_processing', 'Voice Processing'), ('appointment_booking', 'Appointment Booking'), ('emr_integration', 'EMR Integration'), ('notification', 'Notification'), ('analytics', 'Analytics')], max_length=30)),
                ('n8n_workflow_id', models.CharField(max_length=100, unique=True)),
                ('version', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('webhook_url', models.URLField()),
                ('configuration', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'n8n_workflows',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='N8NExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('n8n_execution_id', models.CharField(max_length=100, unique=True)),
                ('input_data', models.JSONField()),
                ('output_data', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('error', 'Error'), ('waiting', 'Waiting'), ('cancelled', 'Cancelled')], default='running', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('execution_time', models.DurationField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='n8n_executions', to='consultations.appointment')),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='n8n_executions', to='consultations.consultation')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='n8n_integration.n8nworkflow')),
            ],
            options={
                'db_table': 'n8n_executions',
                'ordering': ['-created_at'],
            },
        ),
    ]
